---
driver:
  name: vagrant
  memory: 4096

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.18.0

platforms:
  - name: ubuntu-12.04
    run_list:
      - 'recipe[apt::default]'
  - name: ubuntu-14.04
  - name: centos-6.5
  - name: centos-5.10
    attributes:
      cobbler:
        packages:
          - cobbler

suites:
  - name: default
    run_list:
      - 'recipe[cobblerd::default]'
  - name: images
    run_list:
      - 'recipe[cobblerd::centos]'
      - 'recipe[cobblerd::ubuntu]'
  - name: web
    run_list:
      - 'recipe[cobblerd::web]'
    excludes:
      - centos-5.10
